#!/bin/bash

# Description: set up the general installer
# Author: Hawaiideveloper
# Date: 2024-11-03
# Version: 1.0
# Usage: ./script_name.sh [arguments]
# Notes: Additional details, if any

# Initializes a Kubernetes control plane node with specific settings
# Specifies the CIDR (Classless Inter-Domain Routing) 
# block for the pod network.
sudo kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.27.0

# Setup the kube config file
# Creates the directory $HOME/.kube
# Copies the Kubernetes configuration file (admin.conf) generated by kubeadm
# Changes the ownership of the .kube/config file to the current user.

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

